name: Ping Supabase API Every 5 Days

on:
  schedule:
    - cron: '0 0 */5 * *'  # This will run every 5 days at 12:00 AM (UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          set -e  # Exit immediately if a command fails
          echo "Pinging Supabase API..."
          
          # Perform the curl request
          curl -X GET "https://xnvthxttyqnxjgodbitc.supabase.co/rest/v1/FavoriteCurrencyPairs?select=id" \
        
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -w "\nHTTP Status: %{http_code}\n"

