name: Ping Supabase API Every 5 Days

on:
  schedule:
    - cron: '0 0 */5 * *'  # This will run every 5 days at 12:00 AM (UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          set -e  # Exit immediately if a command fails
          echo "Pinging Supabase API..."
          
          # Perform the curl request and capture the HTTP status code
          RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null -X GET "https://xnvthxttyqnxjgodbitc.supabase.co/rest/v1/FavoriteCurrencyPairs?select=id" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}")

          # Check the response code to determine success or failure
          if [ "$RESPONSE" -ne 200 ]; then
              echo "Failed to ping Supabase API. HTTP Status: $RESPONSE"
              exit 1
          else
              echo "Successfully pinged Supabase API. HTTP Status: $RESPONSE"
          fi
